const QuestionApi = [
  {
    id: 1,
    question: "What does HTML stand for?",
    option1: "Hyper Text Markup Language",
    option2: " Hyperlinks and Text Markup Language",
    option3: " Home Tool Markup Language",
    option4: "made Tool Markup Language",
    catagory: "html",

    answer: "Hyper Text Markup Language",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 2,
    question: "Who is making the Web standards?",
    option1: "Mozilla",
    option2: "The world Wide Web Consortium ",
    option3: "Google",
    option4: "microsoft",
    catagory: "html",
    answer: "pranab kumar kandar",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 3,
    question: "Choose the correct HTML element for the largest heading:",
    option1: "<heading>",
    option2: "<h1>",
    option3: "<h6>",
    option4: "<head>",
    catagory: "html",
    answer: "<h1>",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 4,
    question: "What is the correct HTML element for inserting a line break?",
    option1: "<break>",
    option2: "<lb>",
    option3: "<br>",
    option4: "<b>",
    catagory: "html",
    answer: "<br>",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 5,
    question: "What is the correct HTML for adding a background color?",
    option1: "<body bg='yellow'>",
    option2: "<body style='backgroung-color:yellow;'>",
    option3: "<background>yellow<baground>",
    option4: "<b>yellow<b>",
    catagory: "html",
    answer: "<body style='backgroung-color:yellow;'>",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 6,
    question: "Choose the correct HTML element to define important text",
    option1: "<i>",
    option2: "<b>",
    option3: "<strong>",
    option4: "<important>",
    catagory: "html",
    answer: "<strong>",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 7,
    question: "Choose the correct HTML element to define emphasized text",
    option1: "<em>",
    option2: "<i>",
    option3: "<italic>",
    option4: "<e>",
    catagory: "html",
    answer: "<italic>",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 8,
    question: "Which character is used to indicate an end tag?",
    option1: "*",
    option2: "/",
    option3: "<",
    option4: "^",
    catagory: "html",
    answer: "/",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 9,
    question: "How can you open a link in a new tab/browser window?",
    option1: "<a href='url' target='_blank'>",
    option2: "<a href='url' target='new'>",
    option3: "<a href='url' new>",
    option4: "<a href='url' target='_blank_new'>",
    catagory: "html",
    answer: "<a href='url' target='_blank'>",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 10,
    question: "How can you make a numbered list?",
    option1: "<list>",
    option2: "<dl>",
    option3: "<ol>",
    option4: "<ul>",
    catagory: "html",
    answer: "<ol>",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 11,
    question: "What does CSS stand for?",
    option1: "Computer Style Sheet",
    option2: "Creative Style Sheet",
    option3: "Cascading Style Sheet",
    option4: "Colorful Style Sheet",
    catagory: "css",
    answer: "Cascading Style Sheet",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 12,
    question:
      "What is the correct HTML for referring to an external style sheet?",
    option1: "<stylesheet>mystyle.css</stylesheet>",
    option2: "<style src='mystyle.css'>",
    option3: "<link rel='stylesheet' type='text/css' href='mystyle.css'>",
    option4: " <style src='mystyle'>",
    catagory: "css",
    answer: "<link rel='stylesheet' type='text/css' href='mystyle.css'>",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 13,
    question:
      "Where in an HTML document is the correct place to refer to an external style sheet?",
    option1: "In the <head> section",
    option2: "At the end of the document",
    option3: "In the <body> section",
    option4: "In the <div> section",
    catagory: "css",
    answer: "In the <head> section",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 14,
    question: "Which HTML tag is used to define an internal style sheet?",
    option1: " <css>",
    option2: " <script>",
    option3: "<style>",
    option4: "<index>",
    catagory: "css",
    answer: "<style>",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 15,
    question: "what is your name",
    option1: "krishna",
    option2: "krishna kanta",
    option3: "krishna kanta kandar",
    option4: "krishna kanta kandar",
    catagory: "java",
    answer: "krishna kanta kandar",
    selectedAnswer: "Not Answred",
    points: 0,
  },
  {
    id: 16,
    question: "what is your name",
    option1: "krishna",
    option2: "krishna kanta",
    option3: "krishna kanta kandar",
    option4: "krishna kanta kandar",
    catagory: "agriculture",
    answer: "krishna kanta kandar",
    selectedAnswer: "Not Answred",
    points: 0,
  },
];

export default QuestionApi;
