const QuestionApi = [
  {
    id: 1,
    question: "What does HTML stand for?",
    option1: "Hyper Text Markup Language",
    option2: " Hyperlinks and Text Markup Language",
    option3: " Home Tool Markup Language",
    catagory: "html",

    answer: "krishna kanta kandar",
    selectedAnswer: "",
    points: 0,
  },
  {
    id: 2,
    question: "Who is making the Web standards?",
    option1: "pranab",
    option2: "pranab kumar",
    option3: "pranab kumar kandar",
    catagory: "html",
    answer: "pranab kumar kandar",
    selectedAnswer: "",
    points: 0,
  },
  {
    id: 3,
    question: "what is your name",
    option1: "krishna",
    option2: "krishna kanta",
    option3: "krishna kanta kandar",
    catagory: "css",
    answer: "krishna kanta kandar",
    selectedAnswer: "",
    points: 0,
  },
  {
    id: 4,
    question: "what is your name",
    option1: "krishna",
    option2: "krishna kanta",
    option3: "krishna kanta kandar",
    catagory: "css",
    answer: "krishna kanta kandar",
    selectedAnswer: "",
    points: 0,
  },
  {
    id: 5,
    question: "what is your name",
    option1: "krishna",
    option2: "krishna kanta",
    option3: "krishna kanta kandar",
    catagory: "css",
    answer: "krishna kanta kandar",
    selectedAnswer: "",
    points: 0,
  },
  {
    id: 6,
    question: "what is your name",
    option1: "krishna",
    option2: "krishna kanta",
    option3: "krishna kanta kandar",
    catagory: "java",
    answer: "krishna kanta kandar",
    selectedAnswer: "",
    points: 0,
  },
  {
    id: 7,
    question: "what is your name",
    option1: "krishna",
    option2: "krishna kanta",
    option3: "krishna kanta kandar",
    catagory: "java",
    answer: "krishna kanta kandar",
    selectedAnswer: "",
    points: 0,
  },
  {
    id: 7,
    question: "what is your name",
    option1: "krishna",
    option2: "krishna kanta",
    option3: "krishna kanta kandar",
    catagory: "agriculture",
    answer: "krishna kanta kandar",
    selectedAnswer: "",
    points: 0,
  },
];

export default QuestionApi;
